[project]
name = "coinpp"
version = "0.0.1"
authors = [
]
readme = "README.md"
requires-python = ">=3.9"
classifiers = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
ignore = ["E501"]
